In [1]:
import iblatlas as atlas
from iblatlas.atlas import AllenAtlas

In [12]:


from iblatlas.regions import BrainRegions

br = BrainRegions()

In [13]:
import numpy as np
cosmos_indices = np.unique(br.mappings['Cosmos'])
br.acronym[cosmos_indices]

array(['void', 'root', 'Isocortex', 'OLF', 'HPF', 'CTXsp', 'CNU', 'TH',
       'HY', 'MB', 'HB', 'CB'], dtype=object)

In [14]:
cosmos_indices

array([   0,    1,    6,  380,  455,  556,  571,  642,  716,  807,  883,
       1015], dtype=int64)

In [3]:
areas = [
        'MO', 'ORB', 'VIS', 'PIR', 'CTXsp', 'CA1', 'SUB', 'CA3',
        'DG', 'cc', 'VPM', 'VPL', 'PO', 'CP', 'ACB', 'MB']

In [4]:
acronyms, indexes = brain_regions.acronym2index(areas)

In [5]:
indexes

[array([  13, 1340], dtype=int64),
 array([ 253, 1580], dtype=int64),
 array([ 158, 1485], dtype=int64),
 array([ 417, 1744], dtype=int64),
 array([ 556, 1883], dtype=int64),
 array([ 458, 1785], dtype=int64),
 array([ 536, 1863], dtype=int64),
 array([ 468, 1795], dtype=int64),
 array([ 474, 1801], dtype=int64),
 array([1192, 2519], dtype=int64),
 array([ 650, 1977], dtype=int64),
 array([ 648, 1975], dtype=int64),
 array([ 670, 1997], dtype=int64),
 array([ 574, 1901], dtype=int64),
 array([ 576, 1903], dtype=int64),
 array([ 807, 2134], dtype=int64)]

In [6]:
def rgb_to_hex(rgb):
    r,g,b = rgb
    return '#{:02x}{:02x}{:02x}'.format(r, g, b)

In [7]:
hexes = []
for tup in indexes:
    hexes.append(rgb_to_hex(brain_regions.rgb[tup[0]]))

In [46]:
len(hexes)

15

In [37]:
len(areas)

16

In [38]:
len(indexes)

15

In [8]:
hexes

['#1f9d5a',
 '#248a5e',
 '#08858c',
 '#6acbba',
 '#8ada87',
 '#7ed04b',
 '#4fc244',
 '#7ed04b',
 '#7ed04b',
 '#cccccc',
 '#ff8084',
 '#ff8084',
 '#ff909f',
 '#98d6f9',
 '#80cdf8',
 '#ff64ff']